spring:
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: true

security:
  jwt:
    keys:
      public-key-location: ${JWT_PUBLIC_KEY_LOCATION:file:/var/run/secrets/secure-portal/public.pem}
      private-key-location: ${JWT_PRIVATE_KEY_LOCATION:file:/var/run/secrets/secure-portal/private.pem}